### ISSUE TITLE
Shop sign glitch: Says an item is available to be purchased even if there's just a random other block inside the shop. (Tulips)

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#106]
**Describe the bug** *(A clear and concise description of what the bug is)*:
"So Ive got a [sell] sign at shops for deadmans keys. And as I left clicked it, it said that there was 1 deadmans key inside the chest. I go to the chest, some of my random stuff in it that I put in there but no key. I can put any item in this chest and it will tell me that there is a deadmans key inside of it."

**To Reproduce** *(Steps to reproduce the behavior)*:
Set up a shop sign, supposedly Deadmans keys, and place a random item inside the chest (not a key). See if it tells you that it is available to be purchased or not. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
18/12/2020

**Comment by TomLewis** [comment]
The crate plugin has a method to block duping keys when someone is in creative, I wonder if it was blocked thinking that the shop plugin was trying to duplicate it?
The sign shop plugin is ancient and we wont be able to get anything fixed with it thats this bespoke and related to keys.

Wontfix, very small impact.
