### ISSUE TITLE
If a player places a block or chest where the shop's rent sign is, a few hours later the chest either disappears with the items or duplicates signs. 

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#107]
**Describe the bug** *(A clear and concise description of what the bug is)*:
"I placed a chest where the rent sign in my shop was supposed to be and put 2 Saint blades in there, then after a few hours the shop sign replaced the chest with my saints blades in it."

**To Reproduce** *(Steps to reproduce the behavior)*:
Place something where the rent sign is supposed to be, and then wait a few hours. Something wacky will happen to it... it'll either delete or duplicate signs. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
29/12/2020 

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
https://youtu.be/rROGOlgADIc

**Additional context (Delete if this isn't needed)** *(Add any other context about the problem here)*:
This was common knowledge I thought, and I am sure you know about it - but I thought I'd post it anyway. Supposedly he lost both those event swords.

**Comment by TomLewis** [comment]
Intended. 
The shop sign is updating itself, that's it, if the shop sign somehow got removed and cant place it again it'll break onto the floor.

Shop signs can be moved, but only when the shop regenerates after being unrented, otherwise when it goes back to default it will be in a weird place in the shop.

Wontfix.
