### ISSUE TITLE
/trapped doesn't work in spawn protection, says the player has the ability to build there which is not the case. (Solembus13) 

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#70]
**Describe the bug** *(A clear and concise description of what the bug is)*:
When a player does /trapped in a claim that they do not have permission to, the command allows them to escape said claim; in spawn protection, no one has the ability to build, but still cannot use /trapped. Either the command /trapped should be made to work in spawn protection, or the message "You can build here, escape yourself!" should be removed. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Go to /spawn or /warp spawn. Try the /trapped command to escape, it will give you the "You can build here!" message, denying the use of the command. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
8/10/2020 GMT+1 12:41 P.M.

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
![bugboi](https://user-images.githubusercontent.com/69595267/95490269-00394700-0966-11eb-9cfd-5cec26416a4b.png)

**Comment by TomLewis** [comment]
This will be because `/trapped` is from GriefPrevention, and there isnt a GriefPrevention claim, this is a WorldGuard claim so it thinks they can build.
They have to use something like /spawn to get out or a /warp.
The only way to "fix" this is a duct tape, of putting a massive admin claim over the spawn, which is counter productive.
